[package]
name = "localhost"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "localhost"
path = "src/bin/main.rs"

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
